---
blank_issues_enabled: false # default is true
contact_links:
  - name: Discussions
    url: https://github.com/adobe/aem-github-copilot/discussions
    about: >
      Any kind of questions should go onto discussions.
      We recommend using this even if you suspect a bug or have
      a feature request, so the core team can keep the issue tracker
      clean.
